(()=>{const l=document.createElement('link');l.rel='stylesheet';l.href='theme-v2.css?v=20260901-nav2';document.head.appendChild(l)})();const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const root=document.documentElement;

function installGlobalNav(){const header=document.querySelector('header');if(!header)return;header.innerHTML=`<div class="globalNavShell"><div class="wrap globalNav"><a class="brand" href="index.html" aria-label="Pimp My BIM"><img src="assets/Logo_avec%20transparence.png" alt="Pimp My BIM"></a><nav class="globalLinks" aria-label="Navigation principale"><div class="navDrop"><button class="navDropBtn" type="button">Produits <span>⌄</span></button><div class="megaMenu productMenu"><div class="megaIntro"><small>ÉCOSYSTÈME PMB</small><strong>Deux produits.<br>Un même workflow BIM.</strong><p>Produire dans Revit, contrôler et exploiter vos données IFC.</p></div><a href="index.html#revit" class="megaItem"><i>R</i><div><strong>PMB Revit Plugin</strong><span>Automatisation · Data · BIM Health · BCF</span></div></a><a href="index.html#ifc" class="megaItem"><i>IFC</i><div><strong>PMB IFC Platform</strong><span>Viewer · Rules Engine · Analyses · Issues</span></div></a><a href="index.html#pricing" class="megaItem"><i>€</i><div><strong>Tarifs</strong><span>Free, Pro & Premium</span></div></a></div></div><a href="index.html#pricing">Tarifs</a><div class="navDrop"><button class="navDropBtn" type="button">Ressources <span>⌄</span></button><div class="megaMenu resourceMenu"><a href="docs.html" class="megaItem"><i>DOC</i><div><strong>Documentation technique</strong><span>Guides Revit & IFC</span></div></a><a href="updates.html" class="megaItem"><i>↻</i><div><strong>Releases & compatibilité</strong><span>Versions et mises à jour</span></div></a><a href="faq.html" class="megaItem"><i>?</i><div><strong>FAQ</strong><span>Questions fréquentes</span></div></a><a href="legal.html" class="megaItem"><i>§</i><div><strong>Légal & confidentialité</strong><span>Informations éditeur</span></div></a></div></div></nav><div class="globalActions"><div class="controls"><button class="iconbtn" id="themeToggle" aria-label="Changer le thème">☾</button><button class="langbtn" id="langToggle">FR</button></div><a class="navDownload" href="downloads.html">Télécharger <span>→</span></a><button class="mobileMenuBtn" type="button" aria-label="Menu">☰</button></div></div></div>`;const mobile=header.querySelector('.mobileMenuBtn');mobile?.addEventListener('click',()=>header.classList.toggle('mobileOpen'));header.querySelectorAll('.navDropBtn').forEach(btn=>btn.addEventListener('click',e=>{if(innerWidth>900)return;const d=e.currentTarget.closest('.navDrop');header.querySelectorAll('.navDrop.open').forEach(x=>{if(x!==d)x.classList.remove('open')});d.classList.toggle('open')}));}
installGlobalNav();
const dict={fr:{},en:{}};
function applyLang(lang){localStorage.setItem('pmb-site-lang',lang);root.lang=lang;const b=$('#langToggle');if(b)b.textContent=lang.toUpperCase()}
function applyTheme(theme){root.dataset.theme=theme;localStorage.setItem('pmb-site-theme',theme);const b=$('#themeToggle');if(b){b.textContent=theme==='dark'?'☀':'☾';b.setAttribute('aria-label',theme==='dark'?'Switch to light mode':'Switch to dark mode')}}
const savedTheme=localStorage.getItem('pmb-site-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');const savedLang=localStorage.getItem('pmb-site-lang')||((navigator.language||'fr').toLowerCase().startsWith('fr')?'fr':'en');applyTheme(savedTheme);applyLang(savedLang);$('#themeToggle')?.addEventListener('click',()=>applyTheme(root.dataset.theme==='dark'?'light':'dark'));$('#langToggle')?.addEventListener('click',()=>applyLang(root.lang==='fr'?'en':'fr'));
const ambient=$('#ambient');addEventListener('pointermove',e=>{if(!ambient)return;ambient.style.left=e.clientX+'px';ambient.style.top=e.clientY+'px'});const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.14});$$('.reveal').forEach(el=>io.observe(el));const tools=$$('.tool');let toolIndex=0;setInterval(()=>{tools.forEach(x=>x.classList.remove('active'));if(tools.length){tools[toolIndex%tools.length].classList.add('active');toolIndex++}},1450);const model=$('.modelWire');addEventListener('scroll',()=>{if(model){const y=Math.min(10,scrollY*.003);model.style.transform=`perspective(700px) rotateX(${57-y}deg) rotateZ(${-33+y*.35}deg)`}});
const releaseForm=$('#releaseForm');releaseForm?.addEventListener('submit',e=>{e.preventDefault();const email=$('#releaseEmail')?.value||'';location.href=`mailto:contact@pimpmybim.fr?subject=${encodeURIComponent('Inscription aux releases PMB')}&body=${encodeURIComponent('Bonjour,\n\nJe souhaite être prévenu des prochaines releases Pimp My BIM.\n\nEmail : '+email)}`});

function removeUnavailableModules(){const revit=$('#revit');if(!revit)return;const featureTitle=$$('#revit .featureItem strong').find(el=>/Saved selections.*PMB Live/i.test(el.textContent||''));if(featureTitle)featureTitle.textContent='Saved selections & PMB Live';$$('#revit .revitRibbon .tool').forEach(el=>{if(/Opening/i.test(el.textContent||''))el.remove()});}
removeUnavailableModules();

function installRevitFeatureIcons(){const items=$$('#revit .featureList .featureItem');if(!items.length)return;const icons=[['PMB_BimHealth_32x32.png','BIM Health'],['PMB_PimpMyBCF_32x32.png','BCF & Issues'],['PMB_DataManager_32x32.png','Data, codification & livrables'],['PMB_Live_32x32.png','Saved selections & PMB Live']];items.slice(0,4).forEach((item,i)=>{const badge=item.querySelector(':scope > b');if(!badge)return;const [file,label]=icons[i];badge.classList.add('featureIconBadge');badge.innerHTML=`<img src="assets/icons/${file}" alt="${label}" loading="lazy">`;});if(!document.getElementById('pmb-feature-icon-style')){const s=document.createElement('style');s.id='pmb-feature-icon-style';s.textContent=`#revit .featureItem{align-items:center}#revit .featureIconBadge{width:42px!important;height:42px!important;min-width:42px!important;padding:0!important;border-radius:11px!important;display:grid!important;place-items:center!important;background:color-mix(in srgb,var(--lime) 8%,var(--surface2))!important;border:1px solid color-mix(in srgb,var(--lime) 22%,var(--line))!important;overflow:hidden}#revit .featureIconBadge img{width:32px;height:32px;display:block;image-rendering:auto}html[data-theme="dark"] #revit .featureIconBadge{background:#121b10!important;border-color:#34422d!important}`;document.head.appendChild(s);}}
installRevitFeatureIcons();